CREATE TABLE HR.EMPLOYEE (
	FIRST_NAME VARCHAR2(50) NULL,
	LAST_NAME VARCHAR2(50) NULL,
	DEPARTMENT VARCHAR2(100) NULL,
	DESIGNATION VARCHAR2(50) NULL,
	SALARY NUMBER(10,2) NULL
)
TABLESPACE HR_TABLESPACE;

INSERT INTO HR.EMPLOYEE
(FIRST_NAME, LAST_NAME, DEPARTMENT, DESIGNATION, SALARY, ID)
VALUES('Rohit', 'Dey', 'IT', 'Sr. Engineer', 1500000, 1);

INSERT INTO HR.EMPLOYEE
(FIRST_NAME, LAST_NAME, DEPARTMENT, DESIGNATION, SALARY, ID)
VALUES('Vidya', 'Jain', 'IT', 'Sr. Engineer', 1500000, 2);