CREATE TABLE HR.EMPLOYEE (
	FIRST_NAME VARCHAR2(50) NULL,
	LAST_NAME VARCHAR2(50) NULL,
	DEPARTMENT VARCHAR2(100) NULL,
	DESIGNATION VARCHAR2(50) NULL,
	SALARY NUMBER(10,2) NULL
)
TABLESPACE HR_TABLESPACE;
